import ProviderInterface from "./interfaces/provider.interface";

const providers: ProviderInterface[] = [
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    company_name: "Samsung Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    state: "SP",
    district: "Morumbi",
    cep_number: "00000000",
    street: "Av. Jules Rimet",
  },
];

export default providers;
