import ProviderInterface from "./interfaces/provider.interface";

const providers: ProviderInterface[] = [
  {
    id: "00",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "01",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "02",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "03",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "04",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "05",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "06",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "07",
    company_name: "Enterprise Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
  {
    id: "08",
    company_name: "Samsung Limitada S.A",
    fantasy_name: "Enterprise",
    cnpj_number: "00000000000000",
    city: "São Paulo",
    country: "SP",
    district: "Morumbi",
    cep: "00000000",
    street: "Av. Jules Rimet",
  },
];

export default providers;
